config/routes.rb
ProcessViewer::Application.routes.draw do

  devise_for :people
  
root :to => 'pages#home'

resources :people

resources :causes

end

app/models/cause.rb
class Cause < ActiveRecord::Base
	  belongs_to :subject
      belongs_to :court
      belongs_to :judicial_district
      belongs_to :office
      belongs_to :forum

      has_and_belongs_to_many :requirers
      has_many :movimentations

      validates_presence_of :subject, :court, :forum, :judicial_district, :office, :name, :distribution_date

   
end

app/models/court.rb
class Court < ActiveRecord::Base
	has_many :causes

	validates_presence_of :name
end

app/models/forum.rb
class Forum < ActiveRecord::Base
	has_many :causes

	validates_presence_of :name
end

app/models/judicial_district.rb
class JudicialDistrict < ActiveRecord::Base
	has_many :causes

	validates_presence_of :name
end

app/models/movimentation.rb
class Movimentation < ActiveRecord::Base
	belongs_to :cause

	validates_presence_of :cause, :description
end

app/models/office.rb
class Office < ActiveRecord::Base

	has_many :causes
	has_and_belongs_to_many :people

	validates_presence_of :name

end

app/models/person.rb
class Person < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	
	has_many :requirers
	has_and_belongs_to_many :offices

	validates_presence_of :name, :email, :person_type, :user_type, :encrypted_password

end

app/models/requirer.rb
class Requirer < ActiveRecord::Base
	belongs_to :person
	belongs_to :office

	has_and_belongs_to_many :causes

	validates_presence_of :office

end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :causes

	validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/causes_controller.rb
class CausesController < ApplicationController

	def index
		@causes = Cause.all
	end

	def new
		@cause = Cause.new
		@judicial_districts = JudicialDistrict.all
		@courts = Court.all
		@forums = Forum.all
		@subjects = Subject.all
	end

	def show
	end

	def edit
	end

	def delete
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def home
end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  def index
    @people = Person.all
  end

  def show
  end

  def new
    @person = Person.new
  end

  def edit
  end

  def create
    @person = Person.new(person_params)
      if @person.save
        redirect_to @person, notice: 'Person was successfully created.'
      else
        frender action: 'new'
      end
  end

  def update
      if @person.update(person_params)
        redirect_to @person, notice: 'Person was successfully updated.'
      else
        render action: 'edit'
      end
  end

  def destroy
    @person.destroy
    redirect_to people_url
  end

  private
    def set_person
      @person = Person.find(params[:id])
    end

    def person_params
      params.require(:person).permit(:name, :birth_date, :person_type, :user_type, :password, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/causes_helper.rb
module CausesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/causes/_form.html.erb
<%= form_for @cause, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :nome, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :valor, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :value, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :data_da_distribuição, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :distribution_date, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                causes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/causes/index.html.erb
<h1>Lista de Processos</h1>
 
<table class="table table-striped">
  <tr>
    <th>Nome</th>
    <th>Data</th>
    <th>Assunto</th>
    <th></th>
    <th></th>
  </tr>
 
<% @causes.each do |cause| %>
  <tr>
    <td><%= cause.name %></td>
    <td><%= cause.distribution_date %></td>
    <td><%= cause.subject.name %></td>
    <td>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_cause_path(cause.id), :class => 'btn' %>
    </td>
    <td><%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cause_path(cause),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("Você tem certeza?", :default => 'Você tem certeza?')) },
                      :class => 'btn btn-danger' %></td>
  </tr>
<% end %>
</table>
 
<br />

app/views/causes/new.html.erb
<%- model_class = Cause -%>
<div class="page-header">
  <h1>Novo Processo</h1>
</div>
<%= render :partial => 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProcessViewer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-inverse">
	  <div class="navbar-inner">
	    <a class="brand" href="#">Process Viewer</a>
	    <ul class="nav">
	      <li class="active"><a href="#">Home</a></li>
	    </ul>
	    <form class="navbar-form pull-right">
          <input class="span2" type="text" placeholder="Email">
          <input class="span2" type="password" placeholder="Password">
          <button type="submit" class="btn">Sign in</button>
        </form>
	  </div>
	</div>
		<div class="container">
			<div class="span9">
				<%= yield %>
			</div>
		</div>
	</div>	
</body>
</html>

app/views/pages/home.html.erb
<div class="container">
	 <div class="hero-unit">
        <h1>Bem vindo!</h1>
        <p>O process viewer é um portal que permite a fácil integração entre você, seus processos e seus advogados.</p>
        <p><a href="#" class="btn btn-primary btn-large">Inscreva -se &raquo;</a></p>
      </div>

      <div class="row">
        <div class="span4">
          <h2>Clientes</h2>
          <p>Veja o andamento de seus processos. </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
        <div class="span4">
          <h2>Advogados</h2>
          <p>Deixe seus cliente atualizados, sem emails ou telefonemas. </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
       </div>
        <div class="span4">
          <h2>Tour</h2>
          <p>Veja o funcionamento do Process Viewer.</p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; Process Viewer 2013</p>
      </footer>

</div>	

app/views/people/_form.html.erb
<%= form_for @person, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :birth_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :birth_date, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :person_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :person_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :user_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :user_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :password, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                people_path, :class => 'btn' %>
  </div>
<% end %>

app/views/people/edit.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/people/index.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:birth_date) %></th>
      <th><%= model_class.human_attribute_name(:person_type) %></th>
      <th><%= model_class.human_attribute_name(:user_type) %></th>
      <th><%= model_class.human_attribute_name(:password) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= link_to person.id, person_path(person) %></td>
        <td><%= person.name %></td>
        <td><%= person.birth_date %></td>
        <td><%= person.person_type %></td>
        <td><%= person.user_type %></td>
        <td><%= person.password %></td>
        <td><%= person.email %></td>
        <td><%=l person.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_person_path(person), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      person_path(person),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_person_path,
            :class => 'btn btn-primary' %>

app/views/people/new.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/people/show.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @person.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:birth_date) %>:</strong></dt>
  <dd><%= @person.birth_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:person_type) %>:</strong></dt>
  <dd><%= @person.person_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_type) %>:</strong></dt>
  <dd><%= @person.user_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:password) %>:</strong></dt>
  <dd><%= @person.password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @person.email %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              people_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_person_path(@person), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              person_path(@person),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>